//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WOKMWSAuthenticateServiceSoapBinding", Namespace="http://auth.cxf.wokmws.thomsonreuters.com")]
public partial class WOKMWSAuthenticateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback authenticateOperationCompleted;
    
    private System.Threading.SendOrPostCallback closeSessionOperationCompleted;
    
    /// <remarks/>
    public WOKMWSAuthenticateService() {
        this.Url = "http://search.webofknowledge.com/esti/wokmws/ws/WOKMWSAuthenticate";
    }
    
    /// <remarks/>
    public event authenticateCompletedEventHandler authenticateCompleted;
    
    /// <remarks/>
    public event closeSessionCompletedEventHandler closeSessionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://auth.cxf.wokmws.thomsonreuters.com", ResponseNamespace="http://auth.cxf.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string authenticate() {
        object[] results = this.Invoke("authenticate", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginauthenticate(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("authenticate", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string Endauthenticate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void authenticateAsync() {
        this.authenticateAsync(null);
    }
    
    /// <remarks/>
    public void authenticateAsync(object userState) {
        if ((this.authenticateOperationCompleted == null)) {
            this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
        }
        this.InvokeAsync("authenticate", new object[0], this.authenticateOperationCompleted, userState);
    }
    
    private void OnauthenticateOperationCompleted(object arg) {
        if ((this.authenticateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://auth.cxf.wokmws.thomsonreuters.com", ResponseNamespace="http://auth.cxf.wokmws.thomsonreuters.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void closeSession() {
        this.Invoke("closeSession", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincloseSession(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("closeSession", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndcloseSession(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void closeSessionAsync() {
        this.closeSessionAsync(null);
    }
    
    /// <remarks/>
    public void closeSessionAsync(object userState) {
        if ((this.closeSessionOperationCompleted == null)) {
            this.closeSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncloseSessionOperationCompleted);
        }
        this.InvokeAsync("closeSession", new object[0], this.closeSessionOperationCompleted, userState);
    }
    
    private void OncloseSessionOperationCompleted(object arg) {
        if ((this.closeSessionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.closeSessionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void closeSessionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
